name: GigabitEthernet1/0/1 Routed Port Replace
method: PUT
url: https://$DEVICE/restconf/data/Cisco-IOS-XE-native:native/interface/GigabitEthernet=1%2F0%2F1
body:
  content: |-
    {
      "Cisco-IOS-XE-native:GigabitEthernet": {
        "name": "1/0/1",
        "switchport-conf": {
          "switchport": false
        },
        "ip": {
          "address": {
            "primary": {
              "address": "101.1.1.1",
              "mask": "255.255.255.0"
            }
          }
        },
        "ipv6": {
          "address": {
            "prefix-list": [
              {
                "prefix": "3fff:beef:abba:c0fe::1/64"
              }
            ]
          }
        }
      }
    }
  content_type: application/json
auth:
  type: basic
  basic:
    username: $DEVICE_USER
    password: $DEVICE_PASSWORD
headers:
- name: Accept
  value: application/yang-data+json
- name: Content-Type
  value: application/yang-data+json
options:
  verify_ssl: false
