name: GigabitEthernet1/0/1 Access Port Replace
method: PUT
url: https://$DEVICE/restconf/data/Cisco-IOS-XE-native:native/interface/GigabitEthernet=1%2F0%2F1
body:
  content: |-
    {
      "Cisco-IOS-XE-native:GigabitEthernet": {
        "name": "1/0/1",
        "switchport-config": {
          "switchport": {
            "Cisco-IOS-XE-switch:access": {
              "vlan": {
                "vlan": 101
              }
            },
            "Cisco-IOS-XE-switch:mode": {
              "access": {}
            }
          }
        }
      }
    }
  content_type: application/json
auth:
  type: basic
  basic:
    username: $DEVICE_USER
    password: $DEVICE_PASSWORD
headers:
- name: Accept
  value: application/yang-data+json
- name: Content-Type
  value: application/yang-data+json
options:
  verify_ssl: false
