name: Loopback0 Create with IP
method: POST
url: https://$DEVICE/restconf/data/Cisco-IOS-XE-native:native/interface
body:
  content: |-
    {
      "Cisco-IOS-XE-native:Loopback": {
        "name": 0,
        "description": "Configured by RESTCONF",
        "ip": {
          "address": {
            "primary": {
              "address": "172.16.100.1",
              "mask": "255.255.255.0"
            }
          }
        },
        "ipv6": {
          "address": {
            "prefix-list": [
              {
                "prefix": "3fff:c0fe:c0fe:c0fe::1/128"
              }
            ]
          }
        }
      }
    }
  content_type: application/json
auth:
  type: basic
  basic:
    username: $DEVICE_USER
    password: $DEVICE_PASSWORD
headers:
- name: Accept
  value: application/yang-data+json
- name: Content-Type
  value: application/yang-data+json
options:
  verify_ssl: false
