name: Hostname Replace
method: PUT
url: https://$DEVICE/restconf/data/Cisco-IOS-XE-native:native/hostname
body:
  content: |-
    {
      "Cisco-IOS-XE-native:hostname": "sw0x-pod-x"
    }
  content_type: application/json
auth:
  type: basic
  basic:
    username: $DEVICE_USER
    password: $DEVICE_PASSWORD
headers:
- name: Accept
  value: application/yang-data+json
- name: Content-Type
  value: application/yang-data+json
options:
  verify_ssl: false
