name: Routing Protocols Config
url: https://$DEVICE/restconf/data/ietf-routing:routing/routing-instance=default/routing-protocols/routing-protocol
auth:
  type: basic
  basic:
    username: $DEVICE_USER
    password: $DEVICE_PASSWORD
headers:
- name: Accept
  value: application/yang-data+json
- name: Content-Type
  value: application/yang-data+json
options:
  verify_ssl: false
